### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by gsuttie** [ObjectivityLtd/Cake.Deploy.Variables#1]
How do I access the parameters, if I have this:-

ReleaseEnvironment("ist")
    .AddVariable("UserName", "devuser@somedomain.com")
    .AddVariable("Password", "mypassword");

How do I get access to the Password and Username?

**Comment by dwolan** [comment]
Hi,

A good question since this is a missing bit in a Readme file.

If you want to access a variable use a ReleaseVariable alias. The method will return you a value of a variable:
var userName = ReleaseVariable("UserName");

The method returns a value for a current environment so please remember to pass the env parameter while running. Just like in the example below
.\build.ps1 -ScriptArgs '-env="ist"'

Storing password in the cake file directly might not be a good idea. But we can still pass it as an Argument while running.

So, instead of giving a variable a value we can assign a following expression
.AddVariable("Password", x => Argument<string>("Password", ""))

and then while running pass the password as an argument:
.\build.ps1 -ScriptArgs '-env="dev"',  '-Password="mypassword"'

Recently i have notice that there are few missing bits in the Readme file. I will add them shortly.

**Comment by gsuttie** [comment]
can you foreach around them?

**Comment by dwolan** [comment]
Nop

**Comment by gsuttie** [comment]
Got it working this is sweet - many thanks for this and your help ;)
